import type { Metadata } from "next";
import Link from "next/link";
import DashboardShell from "@/components/dashboard-shell";
import StatCard from "@/components/stat-card";
import AppIcon from "@/components/app-icon";
import { I18nProvider } from "@/lib/i18n/provider";

export const metadata: Metadata = { title: "OpenReply — Demo dashboard", robots: { index: false, follow: false } };
const week = [{ day: "Mon", value: 1120 }, { day: "Tue", value: 1320 }, { day: "Wed", value: 1490 }, { day: "Thu", value: 1780 }, { day: "Fri", value: 2050 }, { day: "Sat", value: 2240 }, { day: "Sun", value: 1880 }];
const keywords = [{ label: "GUIA", count: "4,280", width: "94%" }, { label: "LINK", count: "3,640", width: "80%" }, { label: "PRECIO", count: "2,150", width: "57%" }, { label: "CURSO", count: "1,670", width: "43%" }];
const campaigns = [{ name: "Guía de automatización", trigger: "GUIA", sent: "5,284", ctr: "23.6%" }, { name: "Clase gratis de IA", trigger: "MASTERCLASS", sent: "3,716", ctr: "31.4%" }, { name: "Precio del programa", trigger: "PRECIO", sent: "2,842", ctr: "18.1%" }];
const activity = [{ initials: "SM", name: "sofia.mkt", keyword: "GUIA", time: "12 sec ago" }, { initials: "LB", name: "lucas.builds", keyword: "LINK", time: "1 min ago" }, { initials: "MC", name: "maria.crea", keyword: "PRECIO", time: "4 min ago" }];

function DemoDashboard() {
  const maxValue = Math.max(...week.map(item => item.value));
  return <div className="space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-border bg-white px-4 py-2.5 text-xs text-muted"><span><span className="mr-2 rounded bg-surface-hover px-1.5 py-0.5 font-medium text-foreground">Demo</span>Sample data. Sign in to open other sections and your real campaigns.</span><Link href="/demo/flow" className="inline-flex items-center gap-1.5 font-medium text-foreground hover:underline">Try the flow editor <AppIcon name="arrow" className="size-3.5" /></Link></div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="mb-1.5 text-xs font-medium text-muted">YOUR WORKSPACE, AT A GLANCE</p><h1 className="text-3xl font-semibold tracking-[-1.2px] text-foreground">A little less work. More connection.</h1><p className="mt-2 text-sm text-muted">Here’s how your conversations are growing this month.</p></div><Link href="/demo/flow" className="inline-flex w-fit shrink-0 items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-medium text-white hover:bg-accent-hover"><AppIcon name="plus" className="size-4" />Create a campaign</Link></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 sm:gap-4"><StatCard label="DMs sent" value="18,426" trend="32% vs last month" trendUp /><StatCard label="Active campaigns" value="12" trend="3 new this month" trendUp /><StatCard label="Link clicks" value="3,284" trend="24% vs last month" trendUp /><StatCard label="Click-through rate" value="17.8%" trend="4.2 pts vs last month" trendUp /></div>
    <div className="grid gap-5 xl:grid-cols-[1.8fr_1fr]">
      <section className="panel p-5 sm:p-6" aria-labelledby="demo-week-title"><div className="flex items-center justify-between gap-3"><div><h2 id="demo-week-title" className="text-sm font-semibold">Conversations over time</h2><p className="mt-1 text-xs text-muted">Direct messages delivered in the last 7 days</p></div><span className="rounded-md border border-border px-2.5 py-1.5 text-[11px] text-muted">This week</span></div><div className="mt-7 flex h-48 items-end gap-3 sm:gap-5">{week.map((item, index) => <div key={item.day} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] tabular-nums text-muted">{item.value.toLocaleString("en-US")}</span><div className="flex h-[78%] w-full items-end"><div className={`demo-bar w-full rounded-t-[5px] ${index === 5 ? "bg-[#527166]" : "bg-[#d4dfda]"}`} style={{ height: `${item.value / maxValue * 100}%`, animationDelay: `${index * 50}ms` }} /></div><span className="mt-1 text-[11px] text-muted">{item.day}</span></div>)}</div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-xs text-muted"><span className="size-2 rounded-full bg-[#527166]" />12 campaigns working in the background</div></section>
      <section className="panel p-5 sm:p-6" aria-labelledby="demo-keywords-title"><h2 id="demo-keywords-title" className="text-sm font-semibold">What starts the conversation</h2><p className="mt-1 text-xs text-muted">Your most used keywords this month</p><div className="mt-7 space-y-5">{keywords.map(keyword => <div key={keyword.label}><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium">{keyword.label}</span><span className="text-xs tabular-nums text-muted">{keyword.count}</span></div><div className="h-1.5 rounded-full bg-surface-hover"><div className="h-full rounded-full bg-[#9baca4]" style={{ width: keyword.width }} /></div></div>)}</div></section>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.8fr_1fr]">
      <section className="panel overflow-hidden" aria-labelledby="demo-campaigns-title"><div className="flex items-center justify-between gap-3 border-b border-border px-5 py-5 sm:px-6"><h2 id="demo-campaigns-title" className="text-sm font-semibold">Campaign performance</h2><Link href="/demo/flow" className="inline-flex items-center gap-1 text-xs text-muted hover:text-foreground">Explore editor <AppIcon name="arrow" className="size-3.5" /></Link></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-background text-[11px] font-medium text-muted"><tr><th className="px-5 py-3 sm:px-6">Campaign</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Sent</th><th className="px-5 py-3 text-right sm:px-6">CTR</th></tr></thead><tbody className="divide-y divide-border">{campaigns.map(campaign => <tr key={campaign.name} className="hover:bg-background"><td className="px-5 py-4 sm:px-6"><p className="whitespace-nowrap font-medium">{campaign.name}</p><p className="mt-1 text-[10px] text-muted">Keyword · {campaign.trigger}</p></td><td className="px-3 py-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-success/8 px-2 py-1 text-[10px] text-success"><span className="size-1 rounded-full bg-success" />Active</span></td><td className="px-3 py-4 text-right tabular-nums">{campaign.sent}</td><td className="px-5 py-4 text-right tabular-nums sm:px-6">{campaign.ctr}</td></tr>)}</tbody></table></div></section>
      <section className="panel p-5 sm:p-6" aria-labelledby="demo-activity-title"><h2 id="demo-activity-title" className="text-sm font-semibold">Recent activity</h2><p className="mt-1 text-xs text-muted">Small moments. Real connections.</p><div className="mt-4 divide-y divide-border">{activity.map(item => <div key={item.name} className="flex items-center gap-3 py-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-surface-hover text-[11px] font-medium text-muted">{item.initials}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">@{item.name}</p><p className="mt-1 truncate text-[11px] text-muted">Commented {item.keyword}</p></div><div className="text-right"><p className="text-[10px] text-muted">{item.time}</p><span className="mt-1 inline-flex items-center gap-1 text-[10px] text-success"><AppIcon name="check" className="size-3" />Sent</span></div></div>)}</div></section>
    </div>
  </div>;
}
export default function DemoPage() { return <I18nProvider locale="en"><DashboardShell workspaceName="Felimattee Studio" profileImage={null} avatarEditable={false} instagramUsername="felimattee" instagramAccountCount={3}><DemoDashboard /></DashboardShell></I18nProvider>; }
